name: Build Validation

on:
  workflow_run:
    workflows: [".NET CI Pipeline"]
    branches: [main]
    types: [completed]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check if CI succeeded
        if: ${{ github.event.workflow_run.conclusion != 'success' }}
        run: |
          echo "❌ Build failed! Check the CI workflow run."
          exit 1
